spring:
  datasource:
    url: jdbc:mysql://18.222.86.6:3306/IoT?useSSL=false
    #    url: jdbc:mysql://172.31.35.35:3306/IoT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Particle.123456
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
aws:
  accessKey: AKIAINEBVHLBCPP53TZA
  secretKey: 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
  s3:
    baseUrl: https://s3.us-east-1.amazonaws.com/
    mainBucket: gvaproject
server:
  servlet:
    context-path: /api
particle:
  api: https://api.particle.io/v1/
  accessToken: d34a98db1bc8aac6905c7cd30f288e4c0d1c3e6f
app:
  sms:
    sid: AC27d021fe84dfe2db9a402bcd755be4be
    token: 7b398e0f1958d4551e745d86eb07c58d
    phone: +19362419824
    receiver: +18098839517